load_path: "" # only used when separately evaluating a pretrained model
eval: true
batch_size: 64
num_workers: 4
# n_eval: 20
n_eval: 2
eval_every: 5
use_mp: false
num_procs: 20
save_sim_states: false
